spring.application.name=MindExpanse-Backend
server.address=0.0.0.0
server.port=${PORT:8080}
#server.port=8080
spring.mvc.cors.allowed-origins=https://mind-expanse.vercel.app
#  http://localhost:5173/
#  https://mind-expanse.vercel.app
#  http://localhost:5173
#
spring.datasource.url=jdbc:postgresql://dpg-cu7pjglumphs73d84mag-a/mind_expanse_db_b64t
#  jdbc:postgresql://localhost:5432/mind_expanse_db

spring.datasource.username=mind_expanse_db_admin
#  postgres

spring.datasource.password=TMnl77ouADxGrNrevdHlvdaY9pebMqLx
#  open123
#
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.security.oauth2.client.registration.google.client-id=56093430892-go0r5m8mg9u3rfrpusnl1np4rdps1g9m.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.client-secret=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
#spring.security.oauth2.client.registration.google.scope=email,profile


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=corementor.rw@gmail.com
spring.mail.password=yjqgskwhxdbyzkvw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true