spring.application.name=InfinityMind-Backend
server.port=${PORT_NUMBER}
logging.config=classpath:logback-spring.xml
spring.datasource.url=${JDBC_DATABASE_URL}${JDBC_DATABASE_NAME}
#
#  jdbc:postgresql://localhost:5432/mind_expanse_db

spring.datasource.username=${JDBC_DATABASE_USERNAME}
#  postgres
spring.datasource.password=${JDBC_DATABASE_PASSWORD}
#  open123
#  T7p!zX9q@Lm2
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=corementor.rw@gmail.com
spring.mail.password=jqzqnpmliaatolck
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

security.jwt.secret-key=${SECRET_KEY}

#security.jwt.access-expiration-time=900000
#security.jwt.refresh-expiration-time=86400000

security.jwt.access-expiration-time=86400000
security.jwt.refresh-expiration-time=604800000
#
#security.jwt.access-expiration-time=900000
#security.jwt.refresh-expiration-time=2592000000


spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

