spring.application.name=InfinityMind-Backend
server.port=8080
logging.config=classpath:logback-spring.xml
spring.datasource.url=${JDBC_DATABASE_URL}${JDBC_DATABASE_NAME}
#
#  jdbc:postgresql://localhost:5432/mind_expanse_db

spring.datasource.username=${JDBC_DATABASE_USERNAME}
#  postgres
spring.datasource.password=${JDBC_DATABASE_PASSWORD}
#  open123
#  T7p!zX9q@Lm2
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=corementor.rw@gmail.com
spring.mail.password=jqzqnpmliaatolck
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

security.jwt.secret-key="c52ce3add79d1f83d7d6491ee228bee2126978012e17253627e94f4607981e9a0a89833014d45361c351443a937c809f1f362c36e26ef118c1c5ec1edf7a803a5c72c5e5506a96f0198c789fcf352e050ee83620a43c4f1f003e048ea207f7542cf9b76ecefb56c7407c69ff0980a250d415b3a654d6425fa0c0c0b528df53b186674fcd4be53192d5e10b88d42e4bc2001ab386155e3734398092c3d11708dfccb7f72a5011516283ae4503acc67bfdc0f28249d69a70b78986fe13738088bc925973cb166274d325a2c54a9455f78e9c80a05af906baf6e0faac7873129a481b493f4a325781cfbedee1c2c826497a7af78d8c69a572b712f90705bebd3338"
security.jwt.access-expiration-time=900000
security.jwt.refresh-expiration-time=86400000

#security.jwt.expiration-time=86400000
#security.jwt.refresh-expiration-time=604800000
#
#security.jwt.access-expiration-time=900000
#security.jwt.refresh-expiration-time=2592000000


spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

